#!/usr/bin/env bash

# Terminate already running bar instances
killall -q polybar
# If all your bars have ipc enabled, you can also use
# polybar-msg cmd quit

# Launch default bar
echo "---" | tee -a /tmp/poly_default.log /tmp/polybar2.log
polybar default >>/tmp/poly_default.log 2>&1 &


echo "Bars launched..."
